### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Randomjunk999** [scottlamb/hikvision-tftpd#8] opened 2018-07-20 10:27 UTC
I get:

./hikvision_ftfpd.py: 8: ./hikvision_tftpd.py: Syntax Error: newline unexpected

(Running on Ubuntu in VirtualBox with the "$ sudo ./hikvision_tftpd.py --server-ip=172.9.18.80 --filename=digicap.mav" version of the command)

**Comment by Randomjunk999** [comment] 2018-07-23 18:58
Hi,
It's Ubuntu 18.04 with Python 3.6.5 (What are you using to run & I'll try that one.)

**Comment by scottlamb** [comment] 2018-08-06 22:33
Ahh, I developed this with Python 2. So I think this is a dupe of #5. I'm playing around with upgrading, but the workaround is to do `sudo python2 hikvision_tftpd.py ...`

**Closed** 2018-08-07 02:35 UTC
